services:
  houer-api:
    image: 'houer-api:dev'
    build: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - management.endpoints.web.exposure.include=prometheus,info,health
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - jaeger
      - postgres

  # --- Prometheus ------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  # --- Grafana ---------------------------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # --- Jaeger -----------------------
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"
      - "4317:4317"
  
  postgres:
    image: 'postgres:17.5'
    environment:
      - POSTGRES_DB=houer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teste123@
    ports:
      - '5432:5432'
