app:
  verification:
    token:
      expiry-hours: 24
    url-path: /auth/verified
  password-reset:
    token:
      expiry-hours: 2
    notification:
      from-email: noreply@houer.com
      template: password-reset
  cleanup:
    enabled: true
    cron: "0 0 * * * *" # A cada hora no minuto 0
    batch-size: 1000
